apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment12
  labels:
    app: myweb_app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myweb_app
  template:
    metadata:
      name: archerpod
      labels:
        app: myweb_app
    spec:
       containers:
         - name: nginx
           image: nginx
