apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myweb_app
spec:
  selector:
    app: myweb_app
  type: NodePort
  ports:
   -  nodePort: 31000
      targetPort: 80
      port: 80
  
